{% set name = "crowdin-api-client" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5ac052b0d5033fb92eae1eb8b016ea9fab3f1cdf8a0cb0782bfdbe691034005


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests >=2.25.1
    - typing_extensions

test:
  imports:
    - crowdin_api
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/crowdin/crowdin-api-client-python
  summary: Python client library for Crowdin API v2
  description: |
    The Crowdin Python client is a lightweight interface to the Crowdin API.
    It provides common services for making API requests.

    Crowdin API is a full-featured RESTful API that helps you to integrate
    localization into your development process. The endpoints that we use allow
    you to easily make calls to retrieve information and to execute actions needed.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://support.crowdin.com/api/v2/

extra:
  recipe-maintainers:
    - fcollonval
