{% set name = "crowdin-api-client" %}
{% set version = "1.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 870615004c7a3ced17d8537b98efc0fdff8bd9151437e6b01641ccef1a05afad


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - deprecated
    - python >={{ python_min }}
    - requests >=2.31.0
    - typing_extensions

test:
  imports:
    - crowdin_api
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/crowdin/crowdin-api-client-python
  summary: Python client library for Crowdin API v2
  description: |
    The Crowdin Python client is a lightweight interface to the Crowdin API.
    It provides common services for making API requests.

    Crowdin API is a full-featured RESTful API that helps you to integrate
    localization into your development process. The endpoints that we use allow
    you to easily make calls to retrieve information and to execute actions needed.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://support.crowdin.com/api/v2/

extra:
  recipe-maintainers:
    - fcollonval
